<?php


use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme for the paragraph().
 */
function card_price_list_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__card_price_list' => [
      'base hook' => 'paragraph',
    ],
  ];
}



function card_price_list_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, $view_mode, $langcode) {
  if ($entity->getEntityTypeId() === 'paragraph' && $entity->bundle() === 'card_price_list') {
    $build['#attached']['library'][] = 'card_price_list/component_style';
  }
}