<?php

/**
 * @file
 * Paragraph Bundle Image.
 *
 * Filename:     paragraph_bundle_image.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme().
 */
// function card_image_theme($existing, $type, $theme, $path) {
//   return [
//     'paragraph__card_image' => [
//       'base hook' => 'paragraph',
//     ],
//   ];
// }
