<?php

/**
 * @file
 * Primary module hooks for the Paragraph Block module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\paragraph_block\ParagraphBlockService;
use Drupal\paragraph_block\ParagraphBlockServiceInterface;

/**
 * Implements hook_entity_type_alter().
 */
function paragraph_block_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['block_content'])) {
    // Use custom storage and access handlers for block content entities.
    $entity_types['block_content_type']->setHandlerClass('storage', 'Drupal\\paragraph_block\\Entity\\Storage\\CustomBlockContentTypeStorage');
    $entity_types['block_content']->setHandlerClass('storage', 'Drupal\\paragraph_block\\Entity\\Storage\\CustomBlockContentStorage');
    $entity_types['block_content']->setHandlerClass('access', 'Drupal\\paragraph_block\\Access\\ParagraphBlockContentAccessControlHandler');
  }
}

/**
 * Implements hook_block_type_form_alter().
 */
function paragraph_block_block_type_form_alter(array &$form, FormStateInterface &$form_state, string $block_type) {
  if ($block_type === ParagraphBlockServiceInterface::BLOCK_TYPE) {
    // Add custom after-build method to paragraph field widget for UX.
    $form[ParagraphBlockServiceInterface::FIELD_NAME]['widget']['#after_build'][] = [
      ParagraphBlockService::class,
      'elementAfterBuild',
    ];
  }
}
