<?php

/**
 * @file
 * Install, update, and uninstall functions for the "Paragraph block" module.
 */

use Drupal\paragraph_block\ParagraphBlockServiceInterface;

/**
 * Replaces old paragraph_block's with default inline_block's.
 */
function paragraph_block_update_10000(&$sandbox) {
  if (!isset($sandbox['total'])) {
    $rows = \Drupal::database()
      ->select('node__layout_builder__layout', 'layouts')
      ->fields('layouts', ['entity_id'])
      ->groupBy('layouts.entity_id')
      ->execute();

    $sandbox['total'] = count($rows->fetchAll());
    $sandbox['current'] = 0;
    $sandbox['updated'] = 0;
    $sandbox['updated_nodes'] = '';
  }

  $nodes_per_batch = 25;

  // Get a list of nids that have layout overrides.
  $rows = \Drupal::database()
    ->select('node__layout_builder__layout', 'lblayouts')
    ->fields('lblayouts', ['entity_id'])
    ->groupBy('lblayouts.entity_id')
    ->range($sandbox['current'], $nodes_per_batch)
    ->execute();

  $entity_type_manager = \Drupal::entityTypeManager();

  // Update layout overrides.
  foreach ($rows as $row) {
    $updated = FALSE;
    $node = $entity_type_manager->getStorage('node')->load($row->entity_id);

    if (!$node) {
      $sandbox['current']++;
      continue;
    }

    $layout = $node->get('layout_builder__layout')->getValue();
    foreach ($layout as &$layout_section) {
      if (!isset($layout_section['section'])) {
        continue;
      }
      $components = $layout_section['section']->getComponents();
      foreach ($components as &$component) {
        $configuration = $component->get('configuration');
        if (!isset($configuration['id'])) {
          continue;
        }
        [$block_type] = explode(':', $configuration['id']);
        if ($block_type === ParagraphBlockServiceInterface::BLOCK_TYPE) {
          // Update block ID.
          $configuration['id'] = 'inline_block:' . ParagraphBlockServiceInterface::BLOCK_TYPE;
          $component->set('configuration', $configuration);
          $updated = TRUE;
        }
      }
    }

    if ($updated) {
      $node->set('layout_builder__layout', $layout);
      $node->save();
      $sandbox['updated']++;
      $sandbox['updated_nodes'] .= "\n{$node->label()} ({$node->id()})";
    }

    $sandbox['current']++;
  }

  \Drupal::messenger()->addStatus(t('Processed @current from @total layouts, updated @updated.', [
    '@current' => $sandbox['current'],
    '@total' => $sandbox['total'],
    '@updated' => $sandbox['updated'],
  ]));

  if ($sandbox['total'] === 0) {
    $sandbox['#finished'] = 1;
  }
  else {
    $sandbox['#finished'] = $sandbox['current'] / $sandbox['total'];
  }

  if ($sandbox['total'] === $sandbox['current']) {
    \Drupal::messenger()->addStatus(t('The following nodes have been updated: @updated_nodes', [
      '@updated_nodes' => $sandbox['updated_nodes'],
    ]));
  }
}
