<?php

/**
 * @file
 * Paragraph Bundle Image.
 *
 * Filename:     paragraph_bundle_image.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme().
 */
function card_video_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__card_video' => [
      'base hook' => 'paragraph',
    ],
  ];
}


function card_video_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, $view_mode, $langcode) {
  if ($entity->getEntityTypeId() === 'paragraph' && $entity->bundle() === 'card_video') {
    $build['#attached']['library'][] = 'card_video/component_style';
  }
}