<?php

/**
 * @file
 * Paragraph Bundle Image.
 *
 * Filename:     paragraph_bundle_image.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme().
 */
function main_header_theme($existing, $type, $theme, $path) {
  return [
    'block__block_main_header' => [
      'base hook' => 'block',
    ],
  ];
}


function main_header_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, $view_mode, $langcode) {
  if ($entity->getEntityTypeId() === 'block' && $entity->bundle() === 'main_header') {
    $build['#attached']['library'][] = 'main_header/component_style';
  }
}